apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jquery-ingress
  namespace: jquery
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: jquery.avasaramaa.online
    http:
      paths:
      -  backend:
          serviceName: k8s-jquery-svc
          servicePort: 80